spring:
  application:
    name: eureka-consumer
server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true